-- APAGANDO O BANCO DE DADOS CASO EXISTA
drop database if exists DBexercicio07_02;

-- CRIADO A BASE DE DADOS
CREATE DATABASE DBexercicio07_02;

-- CONECTANDO AO BASE DE DADOS
USE DBexercicio07_02;

-- CRIANDO AS TABELAS
create table ALUNO(
	IDALUNO INT NOT NULL
    , NOME VARCHAR(100) NOT NULL
    , PRIMARY KEY (IDALUNO)
);

create table PEDIDO(
	IDPEDIDO INT NOT NULL
	, PRODUTO varchar(45) NOT NULL
    , IDALUNO INT NOT NULL
    , PRIMARY KEY (IDPEDIDO)
    , FOREIGN KEY (IDALUNO) REFERENCES ALUNO(IDALUNO)
);