-- APAGANDO O BANCO DE DADOS CASO EXISTA
drop database if exists DBexercicio07_01;

-- CRIADO A BASE DE DADOS
CREATE DATABASE DBexercicio07_01;

-- CONECTANDO AO BASE DE DADOS
USE DBexercicio07_01;

-- CRIO A TABELA
CREATE TABLE PESSOA_PASSAPORTE (
IDPESSOA INT NOT NULL
, NOME varchar (100) NOT NULL
, IDPASSAPORTE INT
, NUMERO varchar (45)
,primary KEY (IDPESSOA)
); 